project:
  type: website
  output-dir: docs

website:
  title: "Pheno4D Maize Phenotyping"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo

execute:
  echo: true
  warning: false
  message: false
